name: mammorecall

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pytest
  - pip
  - pip:
      - torch
      - torchvision
      - pillow
      - pyyaml
      - wandb
      - pydicom
      - pylibjpeg[all]
      - opencv-python
      - jupyter
      - matplotlib
      - pandas
      - seaborn
      - tqdm
