#!/usr/bin/env python3
"""Plot ROI stats boxplots."""

from __future__ import annotations

import argparse
import os
from collections.abc import Sequence
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

try:
    import matplotlib.pyplot as plt
    import pandas as pd
    import seaborn as sns
except ImportError as exc:
    raise SystemExit(
        "ROI stats plotting requires matplotlib, pandas, and seaborn. "
        "Update the environment with: conda env update -f environment.yml"
    ) from exc


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot ROI stats from CSV.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("processed/roi_stats.csv"),
        help="CSV generated by scripts/calculate_roi_stats.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("processed/roi_stats_plots"),
        help="Directory where plot PNGs are written.",
    )
    return parser.parse_args(argv)


def load_roi_stats(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    required_columns = {"manufacturer", "dataset", "roi_median"}
    missing_columns = required_columns - set(df.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise ValueError(f"Missing required columns in {path}: {missing}")

    df = df.copy()
    df["manufacturer"] = df["manufacturer"].fillna("UNKNOWN").astype(str)
    df["dataset"] = df["dataset"].fillna("UNKNOWN").astype(str)
    df["roi_median"] = pd.to_numeric(df["roi_median"], errors="coerce")
    return df.dropna(subset=["roi_median"])


def save_boxplot(
    df: pd.DataFrame,
    *,
    x: str,
    y: str,
    output_path: Path,
) -> None:
    fig_width = max(8.0, 0.7 * df[x].nunique())
    fig, ax = plt.subplots(figsize=(fig_width, 6.0))
    sns.boxplot(data=df, x=x, y=y, ax=ax)
    ax.set_xlabel(x.replace("_", " ").title())
    ax.set_ylabel(y.replace("_", " ").title())
    ax.tick_params(axis="x", rotation=35)
    fig.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=150)
    plt.close(fig)
    print(output_path)


def main(argv: Sequence[str] | None = None) -> int:
    args = parse_args(argv)
    df = load_roi_stats(args.input)
    if df.empty:
        raise RuntimeError(f"No valid ROI stats rows found in {args.input}")

    save_boxplot(
        df,
        x="dataset",
        y="roi_median",
        output_path=args.output_dir / "roi_median_by_dataset.png",
    )
    save_boxplot(
        df,
        x="manufacturer",
        y="roi_median",
        output_path=args.output_dir / "roi_median_by_manufacturer.png",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
